import type { Metadata } from "next";
import "./globals.css";
import "./font.css";

import { HeroUI } from "@/providers/HeroUI";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it" suppressHydrationWarning>
      <body>
        <HeroUI>{children}</HeroUI>
      </body>
    </html>
  );
}
